'use strict';
import { apiFetch, hasApiConfiguration } from './api.js';
const $ = selector => document.querySelector(selector);
const params = new URLSearchParams(location.search);
const KEY = params.get('key') || '';
const INR = new Intl.NumberFormat('en-IN', {style:'currency', currency:'INR', maximumFractionDigits:2});
const icons = {food:'🍜',groceries:'🛒',grocery:'🛒',travel:'✈️',cab:'🚕',fuel:'⛽',bills:'🧾',rent:'🏠',health:'💊',fitness:'🏋️',entertainment:'🎬',shopping:'🛍️',coffee:'☕',education:'📚',gifts:'🎁'};
let expenses = [];
const state = {preset:'all', payment:'all', q:'', sort:'newest'};

function dateOf(value){ return new Date(/(?:Z|[+-]\d\d:?\d\d)$/i.test(value || '') ? value : `${value}Z`); }
function dayKey(value){ const d=dateOf(value); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
function sum(items){ return items.reduce((total,item)=>total+Number(item.amount||0),0); }
function escapeHtml(value){ const node=document.createElement('div');node.textContent=value ?? '';return node.innerHTML; }
function range(){ const now=new Date(), today=new Date(now.getFullYear(),now.getMonth(),now.getDate()); if(state.preset==='today')return today; if(state.preset==='7')return new Date(today-6*864e5); if(state.preset==='30')return new Date(today-29*864e5); if(state.preset==='month')return new Date(now.getFullYear(),now.getMonth(),1); return null; }
function filtered(){ const from=range(), q=state.q.trim().toLowerCase(); return expenses.filter(item=>{if(from&&dateOf(item.date)<from)return false;if(state.payment!=='all'&&(item.payment_method||'').toLowerCase()!==state.payment)return false;return !q||[item.category,item.description,item.notes,item.payment_method].join(' ').toLowerCase().includes(q);}).sort({newest:(a,b)=>dateOf(b.date)-dateOf(a.date),oldest:(a,b)=>dateOf(a.date)-dateOf(b.date),high:(a,b)=>b.amount-a.amount,low:(a,b)=>a.amount-b.amount}[state.sort]); }
function renderTrend(){ const days=[...Array(7)].map((_,i)=>new Date(Date.now()-(6-i)*864e5)), totals=days.map(day=>sum(expenses.filter(item=>dayKey(item.date)===dayKey(day)))), max=Math.max(...totals,1); $('#trend').innerHTML=totals.map((total,i)=>`<div class="bar" title="${INR.format(total)}" style="height:${Math.max(5,total/max*100)}%"><span>${days[i].toLocaleDateString(undefined,{weekday:'narrow'})}</span></div>`).join(''); }
function label(key){ const today=dayKey(new Date()), yesterday=dayKey(new Date(Date.now()-864e5));if(key===today)return 'Today';if(key===yesterday)return 'Yesterday';return dateOf(`${key}T00:00:00Z`).toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short'}); }
function render(){ const items=filtered(), today=sum(items.filter(item=>dayKey(item.date)===dayKey(new Date()))); $('#total').textContent=INR.format(sum(items));$('#total-sub').textContent=`${items.length} transaction${items.length===1?'':'s'}${items.length!==expenses.length?' · filtered':''}`;$('#stats').innerHTML=`<div class="stat"><small>Today</small><strong>${INR.format(today)}</strong></div><div class="stat"><small>Selected expenses</small><strong>${INR.format(sum(items))}</strong></div>`;renderTrend();const groups=new Map();items.forEach(item=>{const key=dayKey(item.date);groups.set(key,[...(groups.get(key)||[]),item]);}); $('#list').innerHTML=items.length?[...groups].map(([key,rows])=>`<div class="day"><span>${label(key)}</span><span>${INR.format(sum(rows))}</span></div><div class="list">${rows.map(row).join('')}</div>`).join(''):'<div class="empty">No expenses match these filters.</div>'; }
function row(item){const icon=icons[(item.category||'').trim().toLowerCase()]||'🏷️', time=dateOf(item.date).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});return `<article class="tx"><div class="icon">${icon}</div><div class="main"><div class="name">${escapeHtml(item.category||'Expense')}</div><div class="desc">${escapeHtml(item.description||item.notes||'Expense')}</div><div class="meta">${escapeHtml(time)}${item.payment_method?` · ${escapeHtml(item.payment_method)}`:''}</div></div><div class="amount">-${INR.format(item.amount)}</div><button class="delete" data-delete="${escapeHtml(item.id)}" aria-label="Delete expense">×</button></article>`;}
async function load(){if(!hasApiConfiguration()){$('#status').textContent='Set PRIMARY_API_URL and SECONDARY_API_URL in frontend/.env.local';return;}if(!KEY){$('#status').textContent='Add your API key to this page URL';return;}$('#status').textContent='Loading expenses…';try{const response=await apiFetch(`/api/expenses?key=${encodeURIComponent(KEY)}&limit=1000`,{cache:'no-store'});if(response.status===401)throw new Error('Invalid API key');if(!response.ok)throw new Error(`API returned ${response.status}`);const body=await response.json();expenses=body.expenses||[];render();$('#status').textContent='Updated just now';}catch(error){console.error(error);$('#status').textContent=error.message==='Failed to fetch'?'Could not reach API — check its URL and CORS_ORIGINS':error.message;}}
async function remove(id){if(!confirm('Delete this expense?'))return;const response=await apiFetch(`/api/expenses/${encodeURIComponent(id)}?key=${encodeURIComponent(KEY)}`,{method:'DELETE'});if(response.ok){expenses=expenses.filter(item=>item.id!==id);render();}else alert('Could not delete this expense.');}
$('#refresh').onclick=load;$('#preset').onchange=e=>{state.preset=e.target.value;render()};$('#search').oninput=e=>{state.q=e.target.value;render()};$('#sort').onchange=e=>{state.sort=e.target.value;render()};$('#payments').onclick=e=>{const button=e.target.closest('[data-payment]');if(!button)return;state.payment=button.dataset.payment;document.querySelectorAll('[data-payment]').forEach(item=>item.classList.toggle('active',item===button));render();};$('#clear').onclick=()=>{state.preset='all';state.payment='all';state.q='';state.sort='newest';$('#preset').value='all';$('#search').value='';$('#sort').value='newest';document.querySelectorAll('[data-payment]').forEach(item=>item.classList.toggle('active',item.dataset.payment==='all'));render();};$('#list').onclick=e=>{const button=e.target.closest('[data-delete]');if(button)remove(button.dataset.delete);};
load();
